### ISSUE TITLE
phantomjs error on npm install

### ISSUE THREAD

**Issue by s10wen** [1000ch/gulp-stylestats#20]
Wondering if this is an issue? When running `npm install gulp-stylestats --save-dev` got:

```
UNMET PEER DEPENDENCY phantomjs@>=1.9
```

**Comment by 1000ch** [comment]
Would you try following steps?

```ShellSession
$ rm -rf $YOUR_PROJECT/node_modules
$ npm cache clean
$ npm install
```

**Comment by s10wen** [comment]
I noticed some warning in the logs regarding the `$PATH` for `phantomjs`, but seems to have sorted itself out, cheers. :ok_hand:

**Comment by 1000ch** [comment]
:+1:
