### ISSUE TITLE
stylestats is not a function

### ISSUE THREAD

**Issue by nedkelly** [1000ch/gulp-stylestats#21]
I spent hours trying to run the example task in the readme but I always get `TypeError: stylestats is not a function`.

I've managed to get this working now but need to call the task like so:
```javascript
gulp.task('stylestats', function () {
	return gulp.src('./public/assets/css/main.css')
		.pipe(stylestats.default({
			type: 'md',
			outfile: true
		}))
		.pipe(gulp.dest('./'));
});
```

or:
```javascript
gulp.task('stylestats', function () {
	return gulp.src('./public/assets/css/main.css')
		.pipe(stylestats.default())
		.pipe(gulp.dest('./'));
});
```

Obviously `stylestats.default()` is the main difference...

Cheers.

**Comment by teej043** [comment]
Confirmed issue, I get an error `TypeError: object is not a function. ` 
Used to work without issues on my other repo that uses the 1.0.0 version.

**Comment by 1000ch** [comment]
@nedkelly Sorry for delay... @teej043 
Would you try `v1.1.0`?

**Comment by teej043** [comment]
@1000ch 

Installed v.1.1.0 on my other computer and I get this when running gulp.

```
$ gulp
C:\projects\frontend-jeldwen\node_modules\gulp-stylestats\index.js:3
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\projects\frontend-jeldwen\gulpfile.js:25:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by 1000ch** [comment]
@teej043 
Hmm, `"use strict"` is defined in `index.js`.
Which version of your Node.js?

**Comment by 1000ch** [comment]
This problem is fixed in the newest `gulp-stylestats`, would you update?
